# Generated by Django 5.2.9 on 2026-02-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_employee_onboarding_status"),
        ("payroll", "0002_paysliplineitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                (
                    "component_type",
                    models.CharField(
                        choices=[("earning", "Earning"), ("deduction", "Deduction")],
                        max_length=20,
                    ),
                ),
                ("is_taxable", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_components",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ("component_type", "name"),
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalaryComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_components",
                        to="core.employee",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_components",
                        to="payroll.salarycomponent",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "component")},
            },
        ),
    ]
