# Generated by Django 5.2.9 on 2026-02-04 15:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_paysliplineitem_component_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeesalarycomponent",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="employeesalarycomponent",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="employeesalarycomponent",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_assignments",
                to="payroll.salarycomponent",
            ),
        ),
    ]
