# Generated by Django 5.2.9 on 2026-02-04 19:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_employeesalarycomponent_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payslip",
            old_name="allowances",
            new_name="total_deductions",
        ),
        migrations.RenameField(
            model_name="payslip",
            old_name="deductions",
            new_name="total_earnings",
        ),
        migrations.RemoveField(
            model_name="payslip",
            name="basic_pay",
        ),
        migrations.AlterField(
            model_name="payslip",
            name="net_pay",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
