# Generated by Django 5.2.9 on 2026-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("admin", "Admin"),
                    ("accountant", "Accountant"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
