# Generated by Django 5.2.9 on 2026-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_employee_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="onboarding_status",
            field=models.CharField(
                choices=[("invited", "Invited"), ("onboarded", "Onboarded")],
                default="invited",
                max_length=20,
            ),
        ),
    ]
